### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by doopeldedoo** [mmgoodnow/cross-seed#1]
x@y:~$ cross-seed 
/usr/local/lib/node_modules/cross-seed/src/constants.js:2
const SEASON_REGEX = /^(?<title>.+)[. ](?<season>S\d\d)(?!E\d\d)/i;
                     ^

SyntaxError: Invalid regular expression: /^(?<title>.+)[. ](?<season>S\d\d)(?!E\d\d)/: Invalid group
    at Object.<anonymous> (/usr/local/lib/node_modules/cross-seed/src/constants.js:2:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/cross-seed/src/preFilter.js:2:22)
    at Module._compile (module.js:652:30)

**Comment by mmgoodnow** [comment]
What version of node are you using?

**Comment by doopeldedoo** [comment]
Linux 4.15.0-96-generic
node v8.10.0
npm  v3.5.2

**Comment by doopeldedoo** [comment]
Same problem when trying to generate the config file.
```
cross-seed gen-config
/usr/local/lib/node_modules/cross-seed/src/constants.js:2
const SEASON_REGEX = /^(?<title>.+)[. ](?<season>S\d\d)(?!E\d\d)/i;
                     ^

SyntaxError: Invalid regular expression: /^(?<title>.+)[. ](?<season>S\d\d)(?!E\d\d)/: Invalid group
    at Object.<anonymous> (/usr/local/lib/node_modules/cross-seed/src/constants.js:2:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/cross-seed/src/preFilter.js:2:22)
    at Module._compile (module.js:652:30)


```

**Comment by doopeldedoo** [comment]
A similar error occurs when I try to start it with npx:
`npx cross-seed
Invalid regular expression: /^(?<title>.+)[. ](?<season>S\d\d)(?!E\d\d)/: Invalid group`

**Comment by mmgoodnow** [comment]
Yeah, i guess the app requires node 10 then. I can fix the problem though. There may be other bugs from node 8

**Comment by mmgoodnow** [comment]
actually, I found another bug that's not easily fixable using node 8. I recommend that you use node 10.

**Comment by mmgoodnow** [comment]
Clarified the README a bit: https://github.com/mmgoodnow/cross-seed/commit/53f3c0a223d161ebf46c8038bafe3a89ac1e6ae3

I'm going to close this issue. Node 8 is EOL and I have no plans to support it.
