### ISSUE TITLE
"Not defined" error on search specific trackers

### ISSUE THREAD

**Issue by element4l** [mmgoodnow/cross-seed#115]
edit: nevermind, I figured it out. It needs quotes surround the tracker IDs. Might want to add that to config explanation lines. 

---

It works fine if I leave the tracker list blank [] but as soon as I add any tracker, e.g. [hdtorrents], I get this error

 cross-seed search
---/.cross-seed/config.js:13
    trackers: [hdtorrents/results/torznab],
               ^

ReferenceError: hdtorrents is not defined
    at Object.<anonymous> (---/.cross-seed/config.js:13:16)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.getFileConfig (---/.nvm/versions/node/v16.4.2/lib/node_modules/cross-seed/dist/src/configuration.js:51:28)
    at run (---r/.nvm/versions/node/v16.4.2/lib/node_modules/cross-seed/dist/src/cmd.js:37:40)
    at Object.<anonymous> (---/.nvm/versions/node/v16.4.2/lib/node_modules/cross-seed/dist/src/cmd.js:123:1)

**Comment by mmgoodnow** [comment]
Wrap it in quotes
