### ISSUE TITLE
UnhandledPromiseRejectionWarning: ReferenceError: Intl is not defined

### ISSUE THREAD

**Issue by newadventure079** [mmgoodnow/cross-seed#151]
```
DiskStation ~/scripts [1]> cross-seed search --verbose --torrent-dir /volume1/data/Torrents/cross-seed/cross-seed-input --trackers beyond-hd-api
verbose: [configdump] {
  jackettServerUrl: 'http://172.17.0.1:9117',
  jackettApiKey: '[REDACTED]',
  trackers: [ 'beyond-hd-api' ],
  torrentDir: '/volume1/data/Torrents/cross-seed/cross-seed-input',
  outputDir: '/volume1/data/Torrents/cross-seed-output/',
  searchAll: true,
  verbose: true,
  action: 'inject',
  rtorrentRpcUrl: 'http://172.17.0.1:10000/RPC2',
  offset: 0,
  delay: 15,
  includeEpisodes: true
}
info: Validating your configuration...
verbose: [jackett] making search with query ""
verbose: [rtorrent] Calling method download_list with params
info: Your configuration is valid!
verbose: [prefilter] 474 duplicates not selected for searching
info: Found 1555 torrents, 1081 suitable to search for matches
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03 720p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03 1080p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03E10 The Wilderness 720p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03E10 The Wilderness 1080p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03E09 The Grand Jury 720p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03E09 The Grand Jury 1080p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03E08 Stand By Your Man 720p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03E08 Stand By Your Man 1080p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03E07 The Assassination of Monica Lewinsky 720p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03E07 The Assassination of Monica Lewinsky 1080p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03E06 Man Handled 720p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03E06 Man Handled 1080p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03E05 Do You Hear What I Hear 720p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03E05 Do You Hear What I Hear 1080p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03E04 The Telephone Hour 720p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03E04 The Telephone Hour 1080p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03E03 Not To Be Believed 720p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03E03 Not To Be Believed 1080p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03E02 The President Kissed Me 720p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03E02 The President Kissed Me 1080p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S03E01 Exiles 720p AMZN WEB-DL DDP 5.1 H.264-FLUX - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S01 1080p BluRay REMUX AVC DTS-HD MA 5.1-EPSiLON - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S02 1080p AMZN WEB-DL DDP5.1 H.264-NTb - its size does not match
verbose: [decide] American.Crime.Story.S03E01.Exiles.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX.mkv - no match for beyond-hd-api torrent American Crime Story S01 1080p BluRay x264-TURMOiL - its size does not match
(node:7937) UnhandledPromiseRejectionWarning: ReferenceError: Intl is not defined
    at findOnOtherSites (/opt/lib/node_modules/cross-seed/dist/src/pipeline.js:42:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async findMatchesBatch (/opt/lib/node_modules/cross-seed/dist/src/pipeline.js:104:28)
    at async Object.main (/opt/lib/node_modules/cross-seed/dist/src/pipeline.js:136:24)
    at async Command.<anonymous> (/opt/lib/node_modules/cross-seed/dist/src/cmd.js:122:13)
    at async Promise.all (index 0)
    at async run (/opt/lib/node_modules/cross-seed/dist/src/cmd.js:133:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7937) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7937) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mmgoodnow** [comment]
What's your node version?

**Comment by newadventure079** [comment]
`v14.16.1`

**Comment by newadventure079** [comment]
I upgraded to `v14.17.4` and it still fails

**Comment by mmgoodnow** [comment]
Yeah, I'm not sure what's going on there. It also looks like you're using Docker which makes things even more confusing because you're the only one that has reported that error.

**Comment by afraazali** [comment]
I'm on docker and haven't had these issues. I'm also running on an old version of node 12.22.6. I have both the daemon running using the image `mmgoodnow/cross-seed` and also a custom Dockerfile that bases of that same image. The custom dockerfile is so I can simply use cron to run a search periodically.

From the looks of it, you need to run `npm install` as it seems like the `Intl` package is missing from your `node_modules` directory.

**Comment by mmgoodnow** [comment]
Intl should exist by default in the node standard library

**Comment by afraazali** [comment]
Ah ok. I'll spin up another container with the same node version and see if I can reproduce the issue.

**Comment by newadventure079** [comment]
Thanks for the help @afraazali and @mmgoodnow.  I was using a version of node installed by Entware.  I uninstalled that and installed Node from the Synology Package Center and now it works!

**Comment by mmgoodnow** [comment]
Glad to hear that!
