### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: (intermediate value) is not iterable

### ISSUE THREAD

**Issue by newadventure079** [mmgoodnow/cross-seed#154]
```
verbose: [rtorrent] Calling method download_list with params
verbose: [rtorrent] Calling method system.multicall with params [object Object],[object Object],[object Object]
(node:30166) UnhandledPromiseRejectionWarning: TypeError: (intermediate value) is not iterable
    at RTorrent.getTorrentConfiguration (/usr/local/lib/node_modules/cross-seed/dist/src/clients/RTorrent.js:94:61)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RTorrent.inject (/usr/local/lib/node_modules/cross-seed/dist/src/clients/RTorrent.js:133:41)
    at async findOnOtherSites (/usr/local/lib/node_modules/cross-seed/dist/src/pipeline.js:56:28)
    at async Promise.all (index 0)
    at async findMatchesBatch (/usr/local/lib/node_modules/cross-seed/dist/src/pipeline.js:104:28)
    at async Object.main (/usr/local/lib/node_modules/cross-seed/dist/src/pipeline.js:136:24)
    at async Command.<anonymous> (/usr/local/lib/node_modules/cross-seed/dist/src/cmd.js:122:13)
    at async Promise.all (index 0)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:30166) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30166) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mmgoodnow** [comment]
v2.9.3 has more diagnostics for this bug. If you can reproduce it, please report back with what the logs say

**Comment by newadventure079** [comment]
I'll re-open if I see it again
