### ISSUE TITLE
(node:1) UnhandledPromiseRejectionWarning: Error: Unable to parse request body: 

### ISSUE THREAD

**Issue by KyleSanderson** [mmgoodnow/cross-seed#203]
(node:1) UnhandledPromiseRejectionWarning: Error: Unable to parse request body: ""name=Animallica-%22"
    at parseData (file:///usr/src/app/dist/server.js:38:11)
    at Server.handleRequest (file:///usr/src/app/dist/server.js:52:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1) UnhandledPromiseRejectionWarning: Error: Unable to parse request body: ""name=Apogee.Apex.Of.War-%22"
    at parseData (file:///usr/src/app/dist/server.js:38:11)
    at Server.handleRequest (file:///usr/src/app/dist/server.js:52:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) UnhandledPromiseRejectionWarning: Error: Unable to parse request body: ""name=Unsupervised"
    at parseData (file:///usr/src/app/dist/server.js:38:11)
    at Server.handleRequest (file:///usr/src/app/dist/server.js:52:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**Comment by KyleSanderson** [comment]
issue is somewhere else (golang exec) - my apologies.
