### ISSUE TITLE
Unexpected reserved word

### ISSUE THREAD

**Issue by TwistGot** [mmgoodnow/cross-seed#226]
I have installed the package globally using:
` npm install -g cross-seed`

Which seemed to install correctly. However when I try to run the application using:
`cross-seed gen-config`

I am getting the following error:
```
 cross-seed
file:///usr/local/lib/node_modules/cross-seed/dist/cmd.js:34
const fileConfig = await getFileConfig();
                   ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

Anyone have any ideas?

**Comment by TwistGot** [comment]
Ah - RTFM. Wrong Node version was installed.
