### ISSUE TITLE
v4 - DB Creation Fails if Duplicates exist in the cache

### ISSUE THREAD

**Issue by bakerboy448** [mmgoodnow/cross-seed#262]
**Version**

cross-seed --version
4.0.0

**Error**

```
Jun 07 18:54:47 hetz-baker-2004 cross-seed[2241531]: migration file "00-initialSchema" failed
Jun 07 18:54:47 hetz-baker-2004 cross-seed[2241531]: migration failed with error: insert into `torrent` (`file_path`, `info_hash`, `name`) select '/home/bakerboy448/.local/share/qBittorren>
Jun 07 18:54:48 hetz-baker-2004 cross-seed[2241531]: /usr/lib/node_modules/cross-seed/node_modules/knex/lib/dialects/better-sqlite3/index.js:39
Jun 07 18:54:48 hetz-baker-2004 cross-seed[2241531]:     const response = await statement.run(bindings);
Jun 07 18:54:48 hetz-baker-2004 cross-seed[2241531]:                                      ^
Jun 07 18:54:48 hetz-baker-2004 cross-seed[2241531]: SqliteError: insert into `torrent` (`file_path`, `info_hash`, `name`) select '/home/bakerboy448/.local/share/qBittorrent/BT_backup/cfd3>
Jun 07 18:54:48 hetz-baker-2004 cross-seed[2241531]:     at Client_BetterSQLite3._query (/usr/lib/node_modules/cross-seed/node_modules/knex/lib/dialects/better-sqlite3/index.js:39:38)
Jun 07 18:54:48 hetz-baker-2004 cross-seed[2241531]:     at executeQuery (/usr/lib/node_modules/cross-seed/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
Jun 07 18:54:48 hetz-baker-2004 cross-seed[2241531]:     at Client_BetterSQLite3.query (/usr/lib/node_modules/cross-seed/node_modules/knex/lib/client.js:146:12)
Jun 07 18:54:48 hetz-baker-2004 cross-seed[2241531]:     at /usr/lib/node_modules/cross-seed/node_modules/knex/lib/execution/transaction.js:363:24
Jun 07 18:54:48 hetz-baker-2004 cross-seed[2241531]:     at new Promise (<anonymous>)
Jun 07 18:54:48 hetz-baker-2004 cross-seed[2241531]:     at Client_BetterSQLite3.trxClient.query (/usr/lib/node_modules/cross-seed/node_modules/knex/lib/execution/transaction.js:358:12)
Jun 07 18:54:48 hetz-baker-2004 cross-seed[2241531]:     at Runner.query (/usr/lib/node_modules/cross-seed/node_modules/knex/lib/execution/runner.js:130:36)
Jun 07 18:54:48 hetz-baker-2004 cross-seed[2241531]:     at ensureConnectionCallback (/usr/lib/node_modules/cross-seed/node_modules/knex/lib/execution/internal/ensure-connection-callback.j>
Jun 07 18:54:48 hetz-baker-2004 cross-seed[2241531]:     at Runner.ensureConnection (/usr/lib/node_modules/cross-seed/node_modules/knex/lib/execution/runner.js:307:20)
Jun 07 18:54:48 hetz-baker-2004 cross-seed[2241531]:     at async Runner.run (/usr/lib/node_modules/cross-seed/node_modules/knex/lib/execution/runner.js:30:19) {
Jun 07 18:54:48 hetz-baker-2004 cross-seed[2241531]:   code: 'SQLITE_CONSTRAINT_UNIQUE'
Jun 07 18:54:48 hetz-baker-2004 cross-seed[2241531]: }
```

**Description**

Creation of db (migrate from json cache to sqlite) failed due to duplicate torrent entries in the cache

manual review of the cache found it contained 2 pairs of duplicates
- regex101, parse cache with `"filepath":.*"([a-z0-9.\/_]+)` and List with `$1\n`
- copy list to excel and countif to ID duplicates
- search cache file to locate and remove duplicates

**Cache Excerpts**

```
    {
      "filepath": "/home/bakerboy448/.local/share/qBittorrent/BT_backup/def567.torrent",
      "infoHash": "def567",
      "name": "Tenacious.D.in.The.Pick.of.Destiny.2006.1080p.AMZN.WEB-DL.DTS-ES.H.264-TenaciousD.mkv"
    },
    {
      "filepath": "/home/bakerboy448/.local/share/qBittorrent/BT_backup/def567.torrent",
      "infoHash": "def567",
      "name": "Tenacious.D.in.The.Pick.of.Destiny.2006.1080p.AMZN.WEB-DL.DTS-ES.H.264-TenaciousD.mkv"
    },
```

```
      "filepath": "/home/bakerboy448/.local/share/qBittorrent/BT_backup/abc123.torrent",
      "infoHash": "abc123",
      "name": "Tenacious.D.in.The.Pick.of.Destiny.2006.1080p.AMZN.WEB-DL.DTS-ES.H.264-TenaciousD.mkv"
    },
    {
      "filepath": "/home/bakerboy448/.local/share/qBittorrent/BT_backup/abc123.torrent",
      "infoHash": "abc123",
      "name": "Tenacious.D.in.The.Pick.of.Destiny.2006.1080p.AMZN.WEB-DL.DTS-ES.H.264-TenaciousD.mkv"
    },
```

**Suggested Fix**

- deduplicate cache prior to DB creation attempts and warn the user if duplicates detected

**Comment by mmgoodnow** [comment]
v4.0.1
