### ISSUE TITLE
chalk is not defined

### ISSUE THREAD

**Issue by claabs** [mmgoodnow/cross-seed#3]
When running `search`, I occasionally get this error:
```
(node:10) UnhandledPromiseRejectionWarning: ReferenceError: chalk is not defined
    at /usr/local/lib/node_modules/cross-seed/src/torrent.js:14:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async assessResultHelper (/usr/local/lib/node_modules/cross-seed/src/decide.js:30:15)
```

I'm on Node 12 using command line options on the NPM release.

**Comment by mmgoodnow** [comment]
Should be fixed now, was a missing require. https://github.com/mmgoodnow/cross-seed/commit/1c1891905cd66ea0959e5c2b3e7d2a376cc51f43

If it's not you can reopen.
