### ISSUE TITLE
Protocol "magnet:" not supported TypeError

### ISSUE THREAD

**Issue by lindenmj** [mmgoodnow/cross-seed#34]
Some trackers I'm searching with apparently are returning magnet links and not torrent files. I'm not sure where to find more information to share. Here is the error being thrown, in its entirety:

`cross-seed search -t 1337x,limetorrents -i E:\ -s E:\path\ -v -r 60`

```
_http_client.js:152
    throw new ERR_INVALID_PROTOCOL(protocol, expectedProtocol);
    ^

TypeError [ERR_INVALID_PROTOCOL]: Protocol "magnet:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:152:11)
    at Object.request (http.js:46:10)
    at simpleGet (C:\Users\[redacted]\AppData\Roaming\npm\node_modules\cross-seed\node_modules\parse-torrent\node_modules\simple-get\index.js:47:24)
    at ClientRequest.<anonymous> (C:\Users\[redacted]\AppData\Roaming\npm\node_modules\cross-seed\node_modules\parse-torrent\node_modules\simple-get\index.js:59:19)
    at Object.onceWrapper (events.js:417:26)
    at ClientRequest.emit (events.js:310:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at Socket.socketOnData (_http_client.js:469:22)
    at Socket.emit (events.js:310:20) {
  code: 'ERR_INVALID_PROTOCOL'
}
```

**Comment by mmgoodnow** [comment]
Unfortunately magnet links won't work with `cross-seed`. I'll try to see if I can make the error handling better here, but magnet links fundamentally don't contain enough information to verify cross-seed matches, so this, in all likelihood, isn't something the app will ever be able to support.

**Comment by lindenmj** [comment]
I figured as much that magnets wouldn't work. After a little more digging it looks like I have Jackett set to pull magnets instead of torrent files for those indexers too. That option for magnets vs. files isn't present on the private trackers.

**Comment by lindenmj** [comment]
I think it would still be beneficial to work on the error handling for this. Despite using indexers with a torrent file download option, sometimes (for some reason) a magnet is returned and borks the progress, requiring to restart from the beginning of the searching.

**Comment by mmgoodnow** [comment]
I did look into it, but unfortunately it seems that there's no way to catch the exception that gets thrown and resume the program where it left off, at least not with the torrent parsing library I'm using.

**Comment by lindenmj** [comment]
Ah, well that's a bummer! Thanks for looking into it.
