### ISSUE TITLE
TypeError [ERR_INVALID_PROTOCOL]: Protocol "magnet:" not supported. Expected "http:" when trying to search

### ISSUE THREAD

**Issue by DuzAwe** [mmgoodnow/cross-seed#4]
node 12 LTS
NPM 6.14.5

_http_client.js:152
    throw new ERR_INVALID_PROTOCOL(protocol, expectedProtocol);
    ^

TypeError [ERR_INVALID_PROTOCOL]: Protocol "magnet:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:152:11)
    at Object.request (http.js:46:10)
    at simpleGet (/usr/lib/node_modules/cross-seed/node_modules/simple-get/index.js:47:24)
    at ClientRequest.<anonymous> (/usr/lib/node_modules/cross-seed/node_modules/simple-get/index.js:59:19)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at Socket.socketOnData (_http_client.js:469:22)
    at Socket.emit (events.js:315:20) {
  code: 'ERR_INVALID_PROTOCOL'
}

**Comment by DuzAwe** [comment]
Don't use Magnet in an indexer setting
