### ISSUE TITLE
Can't generate Config

### ISSUE THREAD

**Issue by Winblackka** [mmgoodnow/cross-seed#59]
System: Synology DSM 7 
Action: cross-seed gen-config

 cross-seed gen-config
(node:4694) UnhandledPromiseRejectionWarning: TypeError: command.opts is not a function
    at Command.<anonymous> (/usr/local/lib/node_modules/cross-seed/dist/src/cmd.js:82:33)
    at Command.listener [as _actionHandler] (/usr/local/lib/node_modules/cross-seed/node_modules/commander/index.js:922:31)
    at Command._parseCommand (/usr/local/lib/node_modules/cross-seed/node_modules/commander/index.js:1503:14)
    at Command._dispatchSubcommand (/usr/local/lib/node_modules/cross-seed/node_modules/commander/index.js:1443:18)
    at Command._parseCommand (/usr/local/lib/node_modules/cross-seed/node_modules/commander/index.js:1460:12)
    at Command.parse (/usr/local/lib/node_modules/cross-seed/node_modules/commander/index.js:1292:10)
    at Command.parseAsync (/usr/local/lib/node_modules/cross-seed/node_modules/commander/index.js:1318:10)
    at run (/usr/local/lib/node_modules/cross-seed/dist/src/cmd.js:132:31)
    at Object.<anonymous> (/usr/local/lib/node_modules/cross-seed/dist/src/cmd.js:134:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
(node:4694) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4694) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Winblackka** [comment]
Fixed it myself. Thank you! :)

**Comment by mmgoodnow** [comment]
What was the problem? There might still be something I could improve.

**Comment by Winblackka** [comment]
I don't know. I have fixed it by using the config.template.js and saved it as config.js to generate it.
