### ISSUE TITLE
cross-seed gen-config produces an error

### ISSUE THREAD

**Issue by adamwinn** [mmgoodnow/cross-seed#77]
Running `cross-seed gen-config` produces the following error.  Version is `2.3.6`

```
a@DiskStation ~/scripts> cross-seed --version
2.3.6
// All of the configuration can be overridden with command-line flags,

a@DiskStation ~/scripts> cross-seed gen-config
(node:1431) UnhandledPromiseRejectionWarning: TypeError: command.opts is not a function
    at Command.<anonymous> (/opt/lib/node_modules/cross-seed/dist/src/cmd.js:82:33)
    at Command.listener [as _actionHandler] (/opt/lib/node_modules/cross-seed/node_modules/commander/index.js:922:31)
    at Command._parseCommand (/opt/lib/node_modules/cross-seed/node_modules/commander/index.js:1503:14)
    at Command._dispatchSubcommand (/opt/lib/node_modules/cross-seed/node_modules/commander/index.js:1443:18)
    at Command._parseCommand (/opt/lib/node_modules/cross-seed/node_modules/commander/index.js:1460:12)
    at Command.parse (/opt/lib/node_modules/cross-seed/node_modules/commander/index.js:1292:10)
    at Command.parseAsync (/opt/lib/node_modules/cross-seed/node_modules/commander/index.js:1318:10)
    at run (/opt/lib/node_modules/cross-seed/dist/src/cmd.js:132:31)
    at Object.<anonymous> (/opt/lib/node_modules/cross-seed/dist/src/cmd.js:134:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1431) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1431) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mmgoodnow** [comment]
Thanks for letting me know! Fixed in https://github.com/mmgoodnow/cross-seed/releases/tag/v2.3.7
