### ISSUE TITLE
Error: Invalid data: Missing delimiter ":" [0x3a]

### ISSUE THREAD

**Issue by adamwinn** [mmgoodnow/cross-seed#78]
While processing `(1970) Uma No Uta-164.torrent`, cross-seed threw an error.

```
a@DiskStation ~/scripts> cross-seed search --verbose --trackers xxxx
[configdump] {
  jackettServerUrl: 'xxxx',
  jackettApiKey: 'xxxx',
  trackers: [ 'xxxx' ],
  torrentDir: '/volume1/Torrents/reseeds/cross-seed-input/',
  outputDir: '/volume1/Torrents/reseeds/cross-seed-output',
  searchAll: true,
  verbose: true,
  action: 'save',
  offset: 0,
  delay: 15,
  includeEpisodes: false
}
Validating your configuration...
[jackett] making search with query "xxxx"
Your configuration is valid!
Failed to parse ._(1970) Uma No Uta-164.torrent
Error: Invalid data: Missing delimiter ":" [0x3a]
    at Function.decode.find (/opt/lib/node_modules/cross-seed/node_modules/bencode/lib/decode.js:114:9)
    at Function.decode.buffer (/opt/lib/node_modules/cross-seed/node_modules/bencode/lib/decode.js:159:20)
    at Function.decode.next (/opt/lib/node_modules/cross-seed/node_modules/bencode/lib/decode.js:100:21)
    at Object.decode (/opt/lib/node_modules/cross-seed/node_modules/bencode/lib/decode.js:83:17)
    at decodeTorrentFile (/opt/lib/node_modules/cross-seed/node_modules/parse-torrent/index.js:124:23)
    at Object.parseTorrent [as default] (/opt/lib/node_modules/cross-seed/node_modules/parse-torrent/index.js:43:12)
    at Object.parseTorrentFromFilename (/opt/lib/node_modules/cross-seed/dist/src/torrent.js:36:35)
    at createSearcheeFromTorrentFile (/opt/lib/node_modules/cross-seed/dist/src/searchee.js:57:32)
    at Array.map (<anonymous>)
    at Object.loadTorrentDirLight (/opt/lib/node_modules/cross-seed/dist/src/torrent.js:115:10)
```
Torrent name is `(1970) Uma No Uta-164.torrent`

**Comment by mmgoodnow** [comment]
Did the program crash? I believe this is not a bug, just error handling. It looks like the torrent file was malformed.

**Comment by adamwinn** [comment]
I dont think the torrent file is malformed.  It's in my client right now seeding after I added it manually

**Comment by mmgoodnow** [comment]
Some torrent file parsers are more lenient than others on what is accepted. Unfortunately I can't do much here because I use the https://github.com/webtorrent/parse-torrent library to parse torrents, and that's where the error is coming from.
