### ISSUE TITLE
invalid torrentDir path still produces "Your configuration is valid!"

### ISSUE THREAD

**Issue by adamwinn** [mmgoodnow/cross-seed#79]
I inputted an invalid torrentDir path and cross-seed said my config was valid, even tho it's not.  It then later died (presumably when it tried to access torrentDir)

```
a@DiskStation ~/scripts> cross-seed search --verbose --torrent-dir /volume1/Torrents/reseeds/cross-seed-input/DVDs --trackers xxxx
[configdump] {
  jackettServerUrl: 'xxxx',
  jackettApiKey: 'xxxx',
  trackers: [ 'xxxx' ],
  torrentDir: '/volume1/Torrents/reseeds/cross-seed-input/DVDs',
  outputDir: '/volume1/Torrents/reseeds/cross-seed-output',
  searchAll: true,
  verbose: true,
  action: 'save',
  offset: 0,
  delay: 15,
  includeEpisodes: false
}
Validating your configuration...
[jackett] making search with query "xxxx"
Your configuration is valid!
(node:28792) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '/volume1/Torrents/reseeds/cross-seed-input/DVDs'
    at Object.readdirSync (fs.js:1021:3)
    at Object.loadTorrentDirLight (/opt/lib/node_modules/cross-seed/dist/src/torrent.js:112:10)
    at findSearchableTorrents (/opt/lib/node_modules/cross-seed/dist/src/pipeline.js:125:38)
    at Object.main (/opt/lib/node_modules/cross-seed/dist/src/pipeline.js:138:42)
    at Command.<anonymous> (/opt/lib/node_modules/cross-seed/dist/src/cmd.js:121:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async run (/opt/lib/node_modules/cross-seed/dist/src/cmd.js:132:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28792) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:28792) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mmgoodnow** [comment]
Fixed in https://github.com/mmgoodnow/cross-seed/releases/tag/v2.4.1
