### ISSUE TITLE
Error: Unknown XML-RPC tag 'TITLE'

### ISSUE THREAD

**Issue by adamwinn** [mmgoodnow/cross-seed#82]
I was running cross-seed and came across the following error:

```
[191/633] Searching for Fado (2016)
[jackett] making search with query "Fado 2016"
[decide] Fado (2016) - no match for passthepopcorn torrent Fado (2016) 1080p WEB-DL DD+2.0 h264 [1080p / WEB / H.264 / MKV / Checked] - its size does not match
[decide] Fado (2016) - no match for karagarga torrent Fado 2016 Germany [Fado.2016.1080p.WEB-DL.DD2.0.h264.mkv] - its size does not match
[decide] Fado (2016) - no match for cinemaz torrent Fado 2016 1080p WEB-DL AAC2.0 x264 - CMYK - its size does not match
[decide] Fado (2016) - no match for secretcinema torrent Jonas Rothlaender - Fado [2016] SD - its size does not match
[decide] Fado (2016) - no match for passthepopcorn torrent fado.2016.dvdrip.x264-bipolar [672x404 / DVD / x264 / MKV / Scene / Checked] - its size does not match
[decide] Fado (2016) - no match for torrentleech torrent Fado 2016 DVDRip x264-BiPOLAR - its size does not match
[decide] Fado (2016) - no match for alpharatio torrent Fado.2016.DVDRip.x264-BiPOLAR - its size does not match
[decide] Fado (2016) - no match for passthepopcorn torrent Fado.2016.1080p.WEB-DL.AAC2.0.x264-CMYK [1080p / WEB / x264 / MKV / Checked] - its size does not match
[decide] Fado (2016) - no match for torrentleech torrent Fado 2016 GERMAN 720p HDTV x264-muhHD - its size does not match
[decide] Fado (2016) - no match for passthepopcorn torrent Jonas Rothlaender - (2016) Fado [672x576 / DVD / x264 / MKV / Checked] - its size does not match
[decide] Fado (2016) - no match for karagarga torrent Fado 2016 Germany [Jonas.Rothlaender.-.2016.Fado.mkv] - its size does not match
[decide] Fado (2016) - no match for cinemaz torrent Fado 2016 DVDRip DD5.1 x264-KNT - its size does not match
[decide] Fado (2016) - no match for torrentleech torrent Fado German 2016 AC3 DVDRiP x264-KNT - its size does not match
[decide] Fado (2016) - no match for passthepopcorn torrent Fado (2016) [PAL / DVD / DVD9 / VOB IFO / Checked] - the info hash matches a torrent you already have
[rtorrent] Calling method download_list with params []
(node:32051) UnhandledPromiseRejectionWarning: Error: Unknown XML-RPC tag 'TITLE'
    at Deserializer.onError (/opt/lib/node_modules/cross-seed/node_modules/xmlrpc/lib/deserializer.js:109:20)
    at Deserializer.onClosetag (/opt/lib/node_modules/cross-seed/node_modules/xmlrpc/lib/deserializer.js:202:14)
    at SAXStream.emit (events.js:315:20)
    at SAXParser.me._parser.<computed> [as onclosetag] (/opt/lib/node_modules/cross-seed/node_modules/sax/lib/sax.js:258:17)
    at emit (/opt/lib/node_modules/cross-seed/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/opt/lib/node_modules/cross-seed/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/opt/lib/node_modules/cross-seed/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/opt/lib/node_modules/cross-seed/node_modules/sax/lib/sax.js:1436:13)
    at SAXStream.write (/opt/lib/node_modules/cross-seed/node_modules/sax/lib/sax.js:239:18)
    at IncomingMessage.ondata (internal/streams/readable.js:719:22)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32051) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:32051) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mmgoodnow** [comment]
Does this happen immediately upon app startup, or just randomly? Can you reliably reproduce it?

this issue suggests that it could be because of a http/https mismatch. Can you check your configuration?
https://github.com/faisalsami/odoo-xmlrpc/issues/3

**Comment by adamwinn** [comment]
It happened in the middle of a run.  #191 out of 633.  I dont think I've seen it since.  

I think it was in the middle of when rtorrent was really busy and probably threw an error response instead of a valid response.  Kinda like how you see the message in rutorrent sometimes `Bad response from server: (500 [error,list]) Link to XMLRPC failed. May be, rTorrent is down? Connection to rTorrent established.`

**Comment by mmgoodnow** [comment]
> I think it was in the middle of when rtorrent was really busy and probably threw an error response instead of a valid response. Kinda like how you see the message in rutorrent sometimes Bad response from server: (500 [error,list]) Link to XMLRPC failed. May be, rTorrent is down? Connection to rTorrent established.

Ah yeah, that's very possible. I'll see what I can do.

**Comment by mmgoodnow** [comment]
Okay, I added some retrying logic with exponential backoff. https://github.com/mmgoodnow/cross-seed/releases/tag/v2.3.10

The first time it'll go without a delay, then if it fails it'll pause for 1s. Then 2s, 4s, 8s, 16s. That's a total of 31 seconds for rtorrent to get its legs back under its body.

If this turns out to be too long then I'll dial it back a bit.
